# Generated by Django 6.0.3 on 2026-03-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilechangetoken_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profilechangetoken',
            name='change_type',
            field=models.CharField(choices=[('email', 'Email'), ('password', 'Password'), ('verify', 'Verify')], max_length=20),
        ),
    ]
