# Generated by Django 6.0.3 on 2026-03-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_publisher_alter_game_description_alter_game_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='logo',
        ),
    ]
