# Generated by Django 6.0.3 on 2026-03-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechangetoken',
            name='change_type',
            field=models.CharField(choices=[('email', 'Email'), ('email_new', 'Email New'), ('password', 'Password'), ('verify', 'Verify')], max_length=20),
        ),
    ]
